version: '3.4'
services:

# Common Django template for GeoNode and Celery services below
x-common-django:
  &default-common-django
  image: ${COMPOSE_PROJECT_NAME}_django:latest
  restart: unless-stopped
  env_file:
    - .env
  volumes:
    # - '.:/usr/src/openquakeplatform'
    - statics:/mnt/volumes/statics
    - geoserver-data-dir:/geoserver_data/data
    - backup-restore:/backup_restore
    - data:/data
    - tmp:/tmp

volumes:
  statics:
    name: ${COMPOSE_PROJECT_NAME}-statics
  nginx-confd:
    name: ${COMPOSE_PROJECT_NAME}-nginxconfd
  nginx-certificates:
    name: ${COMPOSE_PROJECT_NAME}-nginxcerts
  geoserver-data-dir:
    name: ${COMPOSE_PROJECT_NAME}-gsdatadir
  dbdata:
    name: ${COMPOSE_PROJECT_NAME}-dbdata
  dbbackups:
    name: ${COMPOSE_PROJECT_NAME}-dbbackups
  backup-restore:
    name: ${COMPOSE_PROJECT_NAME}-backup-restore
  data:
    name: ${COMPOSE_PROJECT_NAME}-data
  tmp:
    name: ${COMPOSE_PROJECT_NAME}-tmp
  rabbitmq:
    name: ${COMPOSE_PROJECT_NAME}-rabbitmq

services:

  # PostGIS database.
  db:
    image: geonode/postgis:13
    command: postgres -c "max_connections=${POSTGRESQL_MAX_CONNECTIONS}"
    container_name: ${COMPOSE_PROJECT_NAME}_db
    stdin_open: true
    # tty: true
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dbbackups:/pg_backups
    restart: on-failure
    # uncomment to enable remote connections to postgres
    ports:
      - "127.0.0.1:5432:5432"
    labels:
        org.geonode.component: db
        org.geonode.instance.name: geonode

  # Vanilla RabbitMQ service. This is needed by celery
  rabbitmq:
    image: rabbitmq:3.7-alpine
    restart: on-failure
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    stdin_open: true
    tty: true
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    depends_on:
      - db
    labels:
        org.geonode.component: rabbitmq
        org.geonode.instance.name: geonode
        org.geonode.deployment.name: ${COMPOSE_PROJECT_NAME}

  # Geoserver backend
  geoserver:
    image: geonode/geoserver:2.18.x
    build: geonode-project/docker/geoserver/
    container_name: ${COMPOSE_PROJECT_NAME}_geoserver3
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:8080/geoserver/rest/workspaces/geonode.html"
      interval: 60s
      timeout: 10s
      retries: 1
      start_period: 60s
    stdin_open: true
    #tty: true
    env_file:
      - .env
    volumes:
      - statics:/mnt/volumes/statics
      - geoserver-data-dir:/geoserver_data/data
      - backup-restore:/backup_restore
      - data:/data
      - tmp:/tmp
    restart: on-failure
    depends_on:
      - db
      - data-dir-conf
    labels:
        org.geonode.component: geoserver
        org.geonode.instance.name: geonode


  # Our custom django application. It includes Geonode.
  django:
    << : *default-common-django
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_django
    stdin_open: true
    #tty: true
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:8001/"
      interval: 60s
      timeout: 10s
      retries: 1
      start_period: 60s
    env_file:
      - .env
    environment:
      UWSGI_CMD: uwsgi --ini /usr/src/{{project_name}}/uwsgi.ini
      IS_CELERY: 'False'
    depends_on:
      - db
      - rabbitmq
      - data-dir-conf
    labels:
      org.geonode.component: django
      org.geonode.instance.name: geonode


  # Celery worker that executes celery tasks created by Django.
  celery:
    << : *default-common-django
    image: ${COMPOSE_PROJECT_NAME}_django:latest
    container_name: ${COMPOSE_PROJECT_NAME}_celery
    stdin_open: true
    #tty: true
    environment:
      CELERY_CMD: celery-cmd
      IS_CELERY: 'True'
    depends_on:
      - django
      - db
      - rabbitmq
      - data-dir-conf
    volumes:
      - statics:/mnt/volumes/statics
      - geoserver-data-dir:/geoserver_data/data
      - backup-restore:/backup_restore
      - data:/data
      - tmp:/tmp
    env_file:
      - .env
    labels:
      org.geonode.component: celery
      org.geonode.instance.name: geonode



  # Nginx is serving django static and media files and proxies to django and geonode
  geonode:
    image: geonode/nginx:3.x
    build: geonode-project/docker/nginx/
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    env_file:
      - .env
    #environment:
    #  - HTTPS_HOST=${HTTPS_HOST}
    #  - HTTP_HOST=${HTTP_HOST}
    #  - HTTPS_PORT=${HTTPS_PORT}
    #  - HTTP_PORT=${HTTP_PORT}
    #  - LETSENCRYPT_MODE=${LETSENCRYPT_MODE}
    #  - RESOLVER=127.0.0.11
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - nginx-confd:/etc/nginx
      - nginx-certificates:/geonode-certificates
      - statics:/mnt/volumes/statics
    restart: on-failure

  # Gets and installs letsencrypt certificates
  #letsencrypt:
  #  image: geonode/letsencrypt:latest
  #  build: geonode-project/docker/letsencrypt/
  #  container_name: ${COMPOSE_PROJECT_NAME}_letsencrypt
    #environment:
    #  - HTTPS_HOST=${HTTPS_HOST}
    #- HTTP_HOST=${HTTP_HOST}
    #- ADMIN_EMAIL=${ADMIN_EMAIL}
    #- LETSENCRYPT_MODE=${LETSENCRYPT_MODE}
    #  env_file:
    #     - .env
    #   volumes:
    #     - nginx-certificates:/geonode-certificates
    #  restart: on-failure

  data-dir-conf:
    image: geonode/geoserver_data:2.18.x
    container_name: ${COMPOSE_PROJECT_NAME}_gsconf
    command: /bin/true
    volumes:
      - geoserver-data-dir:/geoserver_data/data
    labels:
        org.geonode.component: conf
        org.geonode.instance.name: geonode
    restart: on-failure
